import { mutation, query, action } from "./_generated/server";
import { api } from "./_generated/api";
import { v } from "convex/values";

// Create a new multi-agent run
export const create = mutation({
  args: {
    datasetName: v.string(),
    uploadId: v.optional(v.id("uploads")),
  },
  handler: async (ctx, args) => {
    const runId = await ctx.db.insert("runs", {
      status: "running",
      step: "Observe",
      activeAgent: "Intake",
      logs: [
        {
          timestamp: Date.now(),
          agent: "Intake",
          message: `Ingesting dataset: ${args.datasetName}`,
          type: "info",
        },
      ],
      uploadId: args.uploadId,
      datasetName: args.datasetName,
      createdAt: Date.now(),
      updatedAt: Date.now(),
    });
    return runId;
  },
});

// Retrieve details for a specific run
export const get = query({
  args: { runId: v.id("runs") },
  handler: async (ctx, args) => {
    return await ctx.db.get(args.runId);
  },
});

// Update the run state machine status/step
export const updateStep = mutation({
  args: {
    runId: v.id("runs"),
    status: v.string(),
    step: v.string(),
    activeAgent: v.string(),
    logMessage: v.string(),
    logType: v.string(), // "info" | "success" | "warn" | "error"
  },
  handler: async (ctx, args) => {
    const run = await ctx.db.get(args.runId);
    if (!run) throw new Error("Run not found");

    const updatedLogs = [
      ...run.logs,
      {
        timestamp: Date.now(),
        agent: args.activeAgent,
        message: args.logMessage,
        type: args.logType,
      },
    ];

    await ctx.db.patch(args.runId, {
      status: args.status,
      step: args.step,
      activeAgent: args.activeAgent,
      logs: updatedLogs,
      updatedAt: Date.now(),
    });
  },
});

// Save insights (anomalies / trends) detected by the Insight agent
export const saveInsights = mutation({
  args: {
    runId: v.id("runs"),
    insights: v.any(),
  },
  handler: async (ctx, args) => {
    await ctx.db.patch(args.runId, {
      insights: args.insights,
      updatedAt: Date.now(),
    });
  },
});

// Save root causes determined by the Root Cause agent
export const saveRootCauses = mutation({
  args: {
    runId: v.id("runs"),
    rootCauses: v.any(),
  },
  handler: async (ctx, args) => {
    await ctx.db.patch(args.runId, {
      rootCauses: args.rootCauses,
      updatedAt: Date.now(),
    });
  },
});

// Save recommendations generated by the Strategy agent
export const saveRecommendations = mutation({
  args: {
    runId: v.id("runs"),
    recommendations: v.any(),
  },
  handler: async (ctx, args) => {
    await ctx.db.patch(args.runId, {
      recommendations: args.recommendations,
      updatedAt: Date.now(),
    });
  },
});

// Save simulation logs generated by the Execution agent
export const saveSimulationLogs = mutation({
  args: {
    runId: v.id("runs"),
    simulationLogs: v.any(),
  },
  handler: async (ctx, args) => {
    await ctx.db.patch(args.runId, {
      simulationLogs: args.simulationLogs,
      updatedAt: Date.now(),
    });
  },
});

// Save evaluation projected outcome generated by the Evaluation agent
export const saveEvaluationResult = mutation({
  args: {
    runId: v.id("runs"),
    evaluationResult: v.any(),
  },
  handler: async (ctx, args) => {
    await ctx.db.patch(args.runId, {
      evaluationResult: args.evaluationResult,
      updatedAt: Date.now(),
    });
  },
});

// Run simulated timeline loop with delays and mock dataset payloads
export const simulateLoop = action({
  args: {
    runId: v.id("runs"),
    datasetName: v.string(),
  },
  handler: async (ctx, args) => {
    const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

    // Choose mock datasets depending on the name
    let mockInsights = {};
    let mockRootCauses = {};
    let mockRecommendations: any[] = [];
    let mockSimulationLogs: any[] = [];
    let mockEvaluationResult = {};

    if (args.datasetName.includes("Shopify")) {
      mockInsights = {
        metrics: [
          { name: "Ad Spend", value: "$4,200", change: "+12%", status: "neutral" },
          { name: "CPA", value: "$38.50", change: "+42%", status: "bad" },
          { name: "Conversion Rate", value: "1.6%", change: "-33%", status: "bad" },
          { name: "Total Orders", value: "1,240", change: "-8%", status: "warn" }
        ],
        anomalies: [
          { title: "Meta CPA Spike", desc: "Meta Ads Customer Acquisition Cost rose suddenly from $27.00 to $38.50." },
          { title: "Checkout Flow Dropoff", desc: "Checkout conversion rate dropped sharply from 2.4% to 1.6%." }
        ]
      };
      
      mockRootCauses = {
        primary: "Competitor Meta Ads Bid Spike",
        detailed: "A key competitor launched a major summer marketing campaign, bidding aggressively on your primary audience keywords. In addition, mobile checkout loading speed increased from 2.1s to 5.2s due to a faulty checkout script update, causing high dropoff rates.",
        metricsEffect: [
          { metric: "CAC Increase", impact: "+$11.50 per acquisition" },
          { metric: "Checkout Dropoff", impact: "Estimated $14,200 in lost weekly revenue" }
        ]
      };

      mockRecommendations = [
        {
          id: "rec1",
          title: "Compress Checkout Scripts & Optimize Layout",
          impact: "high",
          impactScore: 92,
          effort: "low",
          cost: "low",
          desc: "Identify and disable the slow checkout scripts to restore checkout load speeds to < 2.0 seconds.",
          category: "Technical"
        },
        {
          id: "rec2",
          title: "Exclude Low-Performing Lookalike Meta Audiences",
          impact: "medium",
          impactScore: 78,
          effort: "low",
          cost: "low",
          desc: "Shift budget from broad lookalike segments to high-intent custom lists to combat competitive bid pressure.",
          category: "Marketing"
        },
        {
          id: "rec3",
          title: "Activate Cart Abandonment WhatsApp Flow",
          impact: "medium",
          impactScore: 84,
          effort: "medium",
          cost: "medium",
          desc: "Deploy WhatsApp retargeting campaigns with a 10% coupon triggered 15 mins after cart abandonment.",
          category: "Retention"
        }
      ];

      mockSimulationLogs = [
        { message: "Triggering Meta Ads API endpoint update...", status: "success" },
        { message: "Excluding custom audience ID: 294829381...", status: "success" },
        { message: "Drafting checkout speed patch script...", status: "success" },
        { message: "Running minification and lazy loading tests...", status: "success" },
        { message: "Deploying speed optimization patch to production Shopify theme...", status: "success" },
        { message: "Initializing WhatsApp API credentials via twilio hook...", status: "success" },
        { message: "Drafting WhatsApp template: 'Hey {name}, you left items in your cart!'...", status: "success" },
        { message: "Simulation completed successfully.", status: "success" }
      ];

      mockEvaluationResult = {
        before: { conversionRate: 1.6, weeklyRevenue: 48000, cac: 38.5 },
        after: { conversionRate: 2.3, weeklyRevenue: 69000, cac: 29.0 },
        charts: [
          { label: "Conversion Rate", before: 1.6, after: 2.3, suffix: "%" },
          { label: "Weekly Revenue", before: 48000, after: 69000, prefix: "$" },
          { label: "CPA / CAC", before: 38.5, after: 29.0, prefix: "$" }
        ]
      };
    } else if (args.datasetName.includes("SaaS")) {
      mockInsights = {
        metrics: [
          { name: "CTR", value: "3.2%", change: "+150%", status: "good" },
          { name: "Lead Count", value: "850", change: "+45%", status: "good" },
          { name: "Demo Bookings", value: "18", change: "-60%", status: "bad" },
          { name: "Demo Book Rate", value: "2.1%", change: "-72%", status: "bad" }
        ],
        anomalies: [
          { title: "CTR Spike with zero booking growth", desc: "Google Ads campaign CTR spiked by 150%, but demo bookings dropped to less than a third." },
          { title: "Firefox Conversion Drop", desc: "Lead-to-booking conversion rate dropped to 0% for users on Firefox browsers." }
        ]
      };

      mockRootCauses = {
        primary: "Google Ads Click Fraud & Broken Firefox Widget",
        detailed: "An automated click-spam bot targeted our Google search campaign keywords. Concurrently, a CSS z-index update broke the demo scheduling widget on Firefox browsers, preventing genuine leads from booking demos.",
        metricsEffect: [
          { metric: "Wasted Ad Spend", impact: "Estimated $3,500 spent on bot clicks" },
          { metric: "Lost Demos", impact: "Estimated 25 bookable demos missed" }
        ]
      };

      mockRecommendations = [
        {
          id: "rec1",
          title: "Implement IP Click Bot Filtering & Google Ads Review",
          impact: "high",
          impactScore: 95,
          effort: "medium",
          cost: "low",
          desc: "Configure automated IP blocking rules in AdWords and request a click fraud refund from Google.",
          category: "Finance"
        },
        {
          id: "rec2",
          title: "Fix Firefox Demo Calendar Z-Index CSS Bug",
          impact: "high",
          impactScore: 98,
          effort: "low",
          cost: "low",
          desc: "Apply responsive CSS fix to position scheduling calendar modal above navbar layout container.",
          category: "Technical"
        },
        {
          id: "rec3",
          title: "Deploy Interactive Loom Video Widget on Demo Page",
          impact: "medium",
          impactScore: 76,
          effort: "low",
          cost: "low",
          desc: "Embed self-serve video demo to capture engagement for users who prefer not to wait for a calendar slot.",
          category: "Conversion"
        }
      ];

      mockSimulationLogs = [
        { message: "Scanning click logs and aggregating bot IPs...", status: "success" },
        { message: "Exporting 42 blacklisted IP addresses to Google Ads API...", status: "success" },
        { message: "Filing click-fraud dispute report with Google support ticket #49281...", status: "success" },
        { message: "Injecting CSS z-index patches into scheduling components...", status: "success" },
        { message: "Deploying calendar fix to Firefox compatibility test pipeline...", status: "success" },
        { message: "Updating self-serve video assets container layout...", status: "success" },
        { message: "Simulation completed successfully.", status: "success" }
      ];

      mockEvaluationResult = {
        before: { conversionRate: 2.1, weeklyRevenue: 12000, cac: 180 },
        after: { conversionRate: 7.5, weeklyRevenue: 42000, cac: 95 },
        charts: [
          { label: "Demo Book Rate", before: 2.1, after: 7.5, suffix: "%" },
          { label: "Weekly Revenue Runrate", before: 12000, after: 42000, prefix: "$" },
          { label: "Customer Acquisition Cost", before: 180, after: 95, prefix: "$" }
        ]
      };
    } else {
      // Logistics & Retention Analyser
      mockInsights = {
        metrics: [
          { name: "Dispute Count", value: "48", change: "+120%", status: "bad" },
          { name: "Refund Volume", value: "$9,800", change: "+85%", status: "bad" },
          { name: "Transit Duration", value: "7.8 days", change: "+143%", status: "bad" },
          { name: "Customer Retention", value: "91%", change: "-4%", status: "warn" }
        ],
        anomalies: [
          { title: "Transit Delay Spike", desc: "Average order delivery transit times escalated from 3.2 days to 7.8 days." },
          { title: "Chargeback Trigger alert", desc: "Stripe dispute rates reached 1.1%, exceeding the card network warning threshold." }
        ]
      };

      mockRootCauses = {
        primary: "Warehouse Inventory Bottleneck & Carrier Delays",
        detailed: "A local logistics warehouse faced stockout issues coupled with national courier delays, leading to weeks of shipping backlogs. Frustrated buyers filed disputes claiming 'Order not received'.",
        metricsEffect: [
          { metric: "Refund Losses", impact: "$9,800 in active refunds" },
          { metric: "Stripe Penalty risk", impact: "0.4% above standard chargeback margin limit" }
        ]
      };

      mockRecommendations = [
        {
          id: "rec1",
          title: "Automate Stripe Refund Apology Discount Emails",
          impact: "high",
          impactScore: 90,
          effort: "low",
          cost: "low",
          desc: "Auto-detect delayed orders and send an apology email offering a $15 gift card to prevent credit card chargebacks.",
          category: "Retention"
        },
        {
          id: "rec2",
          title: "Reroute Shipments to Amazon FBA Alternate Hubs",
          impact: "high",
          impactScore: 88,
          effort: "medium",
          cost: "medium",
          desc: "Shift stock allocations from the clogged central warehouse to midwestern carrier distribution hubs.",
          category: "Logistics"
        },
        {
          id: "rec3",
          title: "Install Realtime Order Tracking Tracker on Storefront",
          impact: "medium",
          impactScore: 75,
          effort: "low",
          cost: "low",
          desc: "Embed an interactive map widget showing package locations to reduce 'Where is my order' tickets.",
          category: "Technical"
        }
      ];

      mockSimulationLogs = [
        { message: "Connecting to Stripe Webhook configurations...", status: "success" },
        { message: "Adding custom rule: trigger automated email if shipping delay > 5 days...", status: "success" },
        { message: "Drafting template: 'We are truly sorry for the delay' email...", status: "success" },
        { message: "Updating warehouse shipment router endpoints...", status: "success" },
        { message: "Deploying order tracking package components to web layout...", status: "success" },
        { message: "Simulation completed successfully.", status: "success" }
      ];

      mockEvaluationResult = {
        before: { conversionRate: 91, weeklyRevenue: 64000, cac: 4.8 },
        after: { conversionRate: 96, weeklyRevenue: 73000, cac: 1.1 },
        charts: [
          { label: "Retention Rate", before: 91, after: 96, suffix: "%" },
          { label: "Weekly Revenue Value", before: 64000, after: 73000, prefix: "$" },
          { label: "Chargeback / Dispute Rate", before: 4.8, after: 1.1, suffix: "%" }
        ]
      };
    }

    // Loop through the 5 steps sequentially with 1.5s interval sleep
    
    // 1. Observe (Insight)
    await sleep(1500);
    await ctx.runMutation(api.runs.updateStep, {
      runId: args.runId,
      status: "running",
      step: "Observe",
      activeAgent: "Insight",
      logMessage: "Insight Agent scanning raw metrics and detecting KPI anomalies...",
      logType: "info"
    });
    await ctx.runMutation(api.runs.saveInsights, {
      runId: args.runId,
      insights: mockInsights
    });

    // 2. Reason (Root Cause)
    await sleep(1500);
    await ctx.runMutation(api.runs.updateStep, {
      runId: args.runId,
      status: "running",
      step: "Reason",
      activeAgent: "RootCause",
      logMessage: "Root Cause Agent running diagnostics and trace analysis...",
      logType: "info"
    });
    await ctx.runMutation(api.runs.saveRootCauses, {
      runId: args.runId,
      rootCauses: mockRootCauses
    });

    // 3. Decide (Strategy)
    await sleep(1500);
    await ctx.runMutation(api.runs.updateStep, {
      runId: args.runId,
      status: "running",
      step: "Decide",
      activeAgent: "Strategy",
      logMessage: "Strategy Agent generating action recommendations...",
      logType: "info"
    });
    await ctx.runMutation(api.runs.saveRecommendations, {
      runId: args.runId,
      recommendations: mockRecommendations
    });

    // 4. Act (Execution)
    await sleep(1500);
    await ctx.runMutation(api.runs.updateStep, {
      runId: args.runId,
      status: "running",
      step: "Act",
      activeAgent: "Execution",
      logMessage: "Execution Agent simulating action steps & configurations...",
      logType: "info"
    });
    await ctx.runMutation(api.runs.saveSimulationLogs, {
      runId: args.runId,
      simulationLogs: mockSimulationLogs
    });

    // 5. Evaluate (Evaluation)
    await sleep(1500);
    await ctx.runMutation(api.runs.updateStep, {
      runId: args.runId,
      status: "completed",
      step: "Evaluate",
      activeAgent: "Evaluation",
      logMessage: "Evaluation Agent compiling final before-vs-after outcome analysis.",
      logType: "success"
    });
    await ctx.runMutation(api.runs.saveEvaluationResult, {
      runId: args.runId,
      evaluationResult: mockEvaluationResult
    });
  }
});
